package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * CuentasCorrientes generated by hbm2java
 */
public class CuentasCorrientes extends RecursiveTreeObject<CuentasCorrientes> implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -215738452477748132L;
    private Integer id;
    private Propietarios propietarios;
    private String descripcion;
    private BigDecimal monto;
    private Date fecha;
    private Date deletedAt;
    private Date createdAt;
    private Date updatedAt;

    public CuentasCorrientes() {
    }

    public CuentasCorrientes(Propietarios propietarios, String descripcion, BigDecimal monto, Date fecha) {
        this.propietarios = propietarios;
        this.descripcion = descripcion;
        this.monto = monto;
        this.fecha = fecha;
    }

    public CuentasCorrientes(Propietarios propietarios, String descripcion, BigDecimal monto, Date fecha,
            Date deletedAt, Date createdAt, Date updatedAt) {
        this.propietarios = propietarios;
        this.descripcion = descripcion;
        this.monto = monto;
        this.fecha = fecha;
        this.deletedAt = deletedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Propietarios getPropietarios() {
        return this.propietarios;
    }

    public void setPropietarios(Propietarios propietarios) {
        this.propietarios = propietarios;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

}
