package model;
// Generated Dec 3, 2019, 11:54:13 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.NotNull;

/**
 * Entrega generated by hbm2java
 */
public class Entrega extends BaseModel {

    /**
     *
     */
    private static final long serialVersionUID = -3297540390476631917L;
    private Integer id;
    private Propietarios propietarios;
    @NotNull(message = "El campo 'entrega' es obligatorio")
    @DecimalMax(value = "100000", message = "El monto ${formatter.format('%1$.2f', validatedValue)} es mayor "
            + "que {value}")
    private BigDecimal monto;
    private BigDecimal pendiente;
    private Date fecha;
    private boolean deleted;
    private Date deletedAt;
    private Date updatedAt;
    private Date createdAt;
    private String tipo;

    public Entrega() {
    }

    public Entrega(Propietarios propietarios, BigDecimal monto, Date fecha, boolean deleted) {
        this.propietarios = propietarios;
        this.monto = monto;
        this.fecha = fecha;
        this.deleted = deleted;
    }

    public Entrega(Propietarios propietarios, BigDecimal monto, BigDecimal pendiente, Date fecha, boolean deleted,
            Date deletedAt, Date updatedAt, Date createdAt, String tipo) {
        this.propietarios = propietarios;
        this.monto = monto;
        this.fecha = fecha;
        this.deleted = deleted;
        this.deletedAt = deletedAt;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.tipo = tipo;
        this.pendiente = pendiente;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Propietarios getPropietarios() {
        return this.propietarios;
    }

    public void setPropietarios(Propietarios propietarios) {
        this.propietarios = propietarios;
    }

    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    public BigDecimal getPendiente() {
        return this.pendiente;
    }

    public void setPendiente(BigDecimal pendiente) {
        this.pendiente = pendiente;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Override
    public boolean isDeleted() {
        return this.deleted;
    }

    @Override
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    @Override
    public Date getDeletedAt() {
        return this.deletedAt;
    }

    @Override
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public Date getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Override
    public String toString() {
        return "Entrega: " + propietarios + " monto: " + monto + " pendiente: " + pendiente + ", fecha: " + fecha
                + ", tipo: " + tipo;
    }

}
