package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FichasClinicas generated by hbm2java
 */
public class FichasClinicas implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2357760413746833349L;
    private Integer id;
    private Pacientes pacientes;
    private String motivoConsulta;
    private String anamnesis;
    private String medicacionActual;
    private String medicacionAnterior;
    private String estadoNutricion;
    private String estadoSanitario;
    private String aspectoGeneral;
    private String deterDiagComp;
    private String derivaciones;
    private String pronostico;
    private String diagnostico;
    private String exploracion;
    private String evolucion;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;
    private Set retornoses = new HashSet(0);
    private Set internacioneses = new HashSet(0);
    private Set examenGenerals = new HashSet(0);
    private Set historiaClinicas = new HashSet(0);

    public FichasClinicas() {
    }

    public FichasClinicas(Pacientes pacientes, String motivoConsulta) {
        this.pacientes = pacientes;
        this.motivoConsulta = motivoConsulta;
    }

    public FichasClinicas(Pacientes pacientes, String motivoConsulta, String anamnesis, String medicacionActual,
            String medicacionAnterior, String estadoNutricion, String estadoSanitario, String aspectoGeneral,
            String deterDiagComp, String derivaciones, String pronostico, String diagnostico, String exploracion,
            String evolucion, Date createdAt, Date updatedAt, Date deletedAt, Set retornoses, Set internacioneses,
            Set examenGenerals, Set historiaClinicas) {
        this.pacientes = pacientes;
        this.motivoConsulta = motivoConsulta;
        this.anamnesis = anamnesis;
        this.medicacionActual = medicacionActual;
        this.medicacionAnterior = medicacionAnterior;
        this.estadoNutricion = estadoNutricion;
        this.estadoSanitario = estadoSanitario;
        this.aspectoGeneral = aspectoGeneral;
        this.deterDiagComp = deterDiagComp;
        this.derivaciones = derivaciones;
        this.pronostico = pronostico;
        this.diagnostico = diagnostico;
        this.exploracion = exploracion;
        this.evolucion = evolucion;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.retornoses = retornoses;
        this.internacioneses = internacioneses;
        this.examenGenerals = examenGenerals;
        this.historiaClinicas = historiaClinicas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Pacientes getPacientes() {
        return this.pacientes;
    }

    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }

    public String getMotivoConsulta() {
        return this.motivoConsulta;
    }

    public void setMotivoConsulta(String motivoConsulta) {
        this.motivoConsulta = motivoConsulta;
    }

    public String getAnamnesis() {
        return this.anamnesis;
    }

    public void setAnamnesis(String anamnesis) {
        this.anamnesis = anamnesis;
    }

    public String getMedicacionActual() {
        return this.medicacionActual;
    }

    public void setMedicacionActual(String medicacionActual) {
        this.medicacionActual = medicacionActual;
    }

    public String getMedicacionAnterior() {
        return this.medicacionAnterior;
    }

    public void setMedicacionAnterior(String medicacionAnterior) {
        this.medicacionAnterior = medicacionAnterior;
    }

    public String getEstadoNutricion() {
        return this.estadoNutricion;
    }

    public void setEstadoNutricion(String estadoNutricion) {
        this.estadoNutricion = estadoNutricion;
    }

    public String getEstadoSanitario() {
        return this.estadoSanitario;
    }

    public void setEstadoSanitario(String estadoSanitario) {
        this.estadoSanitario = estadoSanitario;
    }

    public String getAspectoGeneral() {
        return this.aspectoGeneral;
    }

    public void setAspectoGeneral(String aspectoGeneral) {
        this.aspectoGeneral = aspectoGeneral;
    }

    public String getDeterDiagComp() {
        return this.deterDiagComp;
    }

    public void setDeterDiagComp(String deterDiagComp) {
        this.deterDiagComp = deterDiagComp;
    }

    public String getDerivaciones() {
        return this.derivaciones;
    }

    public void setDerivaciones(String derivaciones) {
        this.derivaciones = derivaciones;
    }

    public String getPronostico() {
        return this.pronostico;
    }

    public void setPronostico(String pronostico) {
        this.pronostico = pronostico;
    }

    public String getDiagnostico() {
        return this.diagnostico;
    }

    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }

    public String getExploracion() {
        return this.exploracion;
    }

    public void setExploracion(String exploracion) {
        this.exploracion = exploracion;
    }

    public String getEvolucion() {
        return this.evolucion;
    }

    public void setEvolucion(String evolucion) {
        this.evolucion = evolucion;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Set getRetornoses() {
        return this.retornoses;
    }

    public void setRetornoses(Set retornoses) {
        this.retornoses = retornoses;
    }

    public Set getInternacioneses() {
        return this.internacioneses;
    }

    public void setInternacioneses(Set internacioneses) {
        this.internacioneses = internacioneses;
    }

    public Set getExamenGenerals() {
        return this.examenGenerals;
    }

    public void setExamenGenerals(Set examenGenerals) {
        this.examenGenerals = examenGenerals;
    }

    public Set getHistoriaClinicas() {
        return this.historiaClinicas;
    }

    public void setHistoriaClinicas(Set historiaClinicas) {
        this.historiaClinicas = historiaClinicas;
    }

}
