package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * HistoriaClinica generated by hbm2java
 */
public class HistoriaClinica implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -2495196227762558509L;
    private Integer id;
    private FichasClinicas fichasClinicas;
    private String descripcionEvento;
    private Date fechaInicio;
    private Date fechaResolucion;
    private String resultado;
    private String secuelas;
    private String consideraciones;
    private String comentarios;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;

    public HistoriaClinica() {
    }

    public HistoriaClinica(FichasClinicas fichasClinicas, String descripcionEvento, Date fechaInicio) {
        this.fichasClinicas = fichasClinicas;
        this.descripcionEvento = descripcionEvento;
        this.fechaInicio = fechaInicio;
    }

    public HistoriaClinica(FichasClinicas fichasClinicas, String descripcionEvento, Date fechaInicio,
            Date fechaResolucion, String resultado, String secuelas, String consideraciones, String comentarios,
            Date createdAt, Date updatedAt, Date deletedAt) {
        this.fichasClinicas = fichasClinicas;
        this.descripcionEvento = descripcionEvento;
        this.fechaInicio = fechaInicio;
        this.fechaResolucion = fechaResolucion;
        this.resultado = resultado;
        this.secuelas = secuelas;
        this.consideraciones = consideraciones;
        this.comentarios = comentarios;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public FichasClinicas getFichasClinicas() {
        return this.fichasClinicas;
    }

    public void setFichasClinicas(FichasClinicas fichasClinicas) {
        this.fichasClinicas = fichasClinicas;
    }

    public String getDescripcionEvento() {
        return this.descripcionEvento;
    }

    public void setDescripcionEvento(String descripcionEvento) {
        this.descripcionEvento = descripcionEvento;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaResolucion() {
        return this.fechaResolucion;
    }

    public void setFechaResolucion(Date fechaResolucion) {
        this.fechaResolucion = fechaResolucion;
    }

    public String getResultado() {
        return this.resultado;
    }

    public void setResultado(String resultado) {
        this.resultado = resultado;
    }

    public String getSecuelas() {
        return this.secuelas;
    }

    public void setSecuelas(String secuelas) {
        this.secuelas = secuelas;
    }

    public String getConsideraciones() {
        return this.consideraciones;
    }

    public void setConsideraciones(String consideraciones) {
        this.consideraciones = consideraciones;
    }

    public String getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

}
