package model;
// Generated Apr 30, 2019 5:08:23 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * Localidades generated by hbm2java
 */
public class Localidades extends RecursiveTreeObject<Localidades> implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 7821799036615290017L;
    private Integer id;
    private Integer codPostal;
    private String nombre;
    private int provinciaId;
    private boolean deleted;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;
    private Set<Propietarios> propietarioses = new HashSet<Propietarios>(0);
    private Provincias provincias;

    public Localidades() {
    }

    public Localidades(String nombre, int provinciaId, boolean deleted) {
        this.nombre = nombre;
        this.provinciaId = provinciaId;
        this.deleted = deleted;
    }

    public Localidades(Integer codPostal, String nombre, int provinciaId, boolean deleted, Date createdAt,
            Date updatedAt, Date deletedAt, Set<Propietarios> propietarioses, Provincias provincias) {
        this.codPostal = codPostal;
        this.nombre = nombre;
        this.provinciaId = provinciaId;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.propietarioses = propietarioses;
        this.provincias = provincias;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCodPostal() {
        return this.codPostal;
    }

    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getProvinciaId() {
        return this.provinciaId;
    }

    public void setProvinciaId(int provinciaId) {
        this.provinciaId = provinciaId;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Set<Propietarios> getPropietarioses() {
        return this.propietarioses;
    }

    public void setPropietarioses(Set<Propietarios> propietarioses) {
        this.propietarioses = propietarioses;
    }

    public Provincias getProvincias() {
        return this.provincias;
    }

    public void setProvincias(Provincias provincias) {
        this.provincias = provincias;
    }

}
