package model;
// Generated Apr 19, 2019 8:34:17 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * Localidades generated by hbm2java
 */
public class Localidades extends RecursiveTreeObject<Localidades> implements java.io.Serializable {

    private Integer id;
    private Integer codPostal;
    private String nombre;
    private boolean deleted;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;
    private Set propietarioses = new HashSet(0);
    private Provincias provincia;

    public Localidades() {
    }

    public Localidades(String nombre, Provincias provincia, boolean deleted) {
        this.nombre = nombre;
        this.provincia = provincia;
        this.deleted = deleted;
    }

    public Localidades(Integer codPostal, String nombre, Provincias provincia, boolean deleted, Date createdAt,
            Date updatedAt, Date deletedAt, Set propietarioses, Provincias provincias) {
        this.codPostal = codPostal;
        this.nombre = nombre;
        this.provincia = provincia;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.propietarioses = propietarioses;
        this.provincia = provincia;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCodPostal() {
        return this.codPostal;
    }

    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Set getPropietarioses() {
        return this.propietarioses;
    }

    public void setPropietarioses(Set propietarioses) {
        this.propietarioses = propietarioses;
    }

    public Provincias getProvincia() {
        return this.provincia;
    }

    public void setProvincias(Provincias provincia) {
        this.provincia = provincia;
    }

}
