package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Localidades generated by hbm2java
 */
public class Localidades implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -3030066905131677377L;
    private Integer id;
    private String nombre;
    private int provinciaId;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;
    private Set propietarioses = new HashSet(0);

    public Localidades() {
    }

    public Localidades(String nombre, int provinciaId) {
        this.nombre = nombre;
        this.provinciaId = provinciaId;
    }

    public Localidades(String nombre, int provinciaId, Date createdAt, Date updatedAt, Date deletedAt,
            Set propietarioses) {
        this.nombre = nombre;
        this.provinciaId = provinciaId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.propietarioses = propietarioses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getProvinciaId() {
        return this.provinciaId;
    }

    public void setProvinciaId(int provinciaId) {
        this.provinciaId = provinciaId;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Set getPropietarioses() {
        return this.propietarioses;
    }

    public void setPropietarioses(Set propietarioses) {
        this.propietarioses = propietarioses;
    }

}
