package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes extends RecursiveTreeObject<Pacientes> implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 6956584964912077781L;
    private Integer id;
    @NotNull(message = "El campo 'propietario' es requerido.")
    private Propietarios propietarios;
    @NotEmpty(message = "El campo 'nombre' es requerido.")
    @Size(max = 191, message = "El campo 'nombre' no debe ser mayor a {max} caracteres.")
    private String nombre;
    @NotEmpty(message = "El campo 'especie' es requerido.")
    @Size(max = 191, message = "El campo 'especie' no debe ser mayor a {max} caracteres.")
    private String especie;
    @NotEmpty(message = "El campo 'raza' es requerido.")
    @Size(max = 191, message = "El campo 'raza' no debe ser mayor a {max} caracteres.")
    private String raza;
    @NotEmpty(message = "El campo 'sexo' es requerido.")
    private String sexo;
    @NotEmpty(message = "El campo 'temperamento' es requerido.")
    @Size(max = 191, message = "El campo 'temperamento' no debe ser mayor a {max} caracteres.")
    private String temperamento;
    @NotEmpty(message = "El campo 'pelaje' es requerido.")
    @Size(max = 191, message = "El campo 'pelaje' no debe ser mayor a {max} caracteres.")
    private String pelaje;
    private Date fechaNacimiento;
    @Size(max = 191, message = "El campo 'resultado' no debe ser mayor a {max} caracteres.")
    private String foto;
    private boolean deleted;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;
    private Set<FichasClinicas> fichasClinicases = new HashSet<FichasClinicas>(0);
    private Set<Desparasitaciones> desparasitacioneses = new HashSet<Desparasitaciones>(0);
    private Set<Vacunas> vacunases = new HashSet<Vacunas>(0);
    private Set<ExamenGeneral> examenGenerals = new HashSet<ExamenGeneral>(0);
    private Set<Internaciones> internacioneses = new HashSet<Internaciones>(0);

    public Pacientes() {
    }

    public Pacientes(String nombre, String especie, String raza, String sexo, String temperamento, String pelaje,
            boolean deleted) {
        this.nombre = nombre;
        this.especie = especie;
        this.raza = raza;
        this.sexo = sexo;
        this.temperamento = temperamento;
        this.pelaje = pelaje;
        this.deleted = deleted;
    }

    public Pacientes(Propietarios propietarios, String nombre, String especie, String raza, String sexo,
            String temperamento, String pelaje, Date fechaNacimiento, String foto, Date createdAt, boolean deleted,
            Date updatedAt, Date deletedAt, Set<FichasClinicas> fichasClinicases,
            Set<Desparasitaciones> desparasitacioneses, Set<Vacunas> vacunases) {
        this.propietarios = propietarios;
        this.nombre = nombre;
        this.especie = especie;
        this.raza = raza;
        this.sexo = sexo;
        this.temperamento = temperamento;
        this.pelaje = pelaje;
        this.fechaNacimiento = fechaNacimiento;
        this.foto = foto;
        this.createdAt = createdAt;
        this.deleted = deleted;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.fichasClinicases = fichasClinicases;
        this.desparasitacioneses = desparasitacioneses;
        this.vacunases = vacunases;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Propietarios getPropietarios() {
        return this.propietarios;
    }

    public void setPropietarios(Propietarios propietarios) {
        this.propietarios = propietarios;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getEspecie() {
        return this.especie;
    }

    public void setEspecie(String especie) {
        this.especie = especie;
    }

    public String getRaza() {
        return this.raza;
    }

    public void setRaza(String raza) {
        this.raza = raza;
    }

    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public String getTemperamento() {
        return this.temperamento;
    }

    public void setTemperamento(String temperamento) {
        this.temperamento = temperamento;
    }

    public String getPelaje() {
        return this.pelaje;
    }

    public void setPelaje(String pelaje) {
        this.pelaje = pelaje;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getFoto() {
        return this.foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Set<FichasClinicas> getFichasClinicases() {
        return this.fichasClinicases;
    }

    public void setFichasClinicases(Set<FichasClinicas> fichasClinicases) {
        this.fichasClinicases = fichasClinicases;
    }

    public Set<Desparasitaciones> getDesparasitacioneses() {
        return this.desparasitacioneses;
    }

    public void setDesparasitacioneses(Set<Desparasitaciones> desparasitacioneses) {
        this.desparasitacioneses = desparasitacioneses;
    }

    public Set<Vacunas> getVacunases() {
        return this.vacunases;
    }

    public void setVacunases(Set<Vacunas> vacunases) {
        this.vacunases = vacunases;
    }

    public Set<ExamenGeneral> getExamenGenerals() {
        return this.examenGenerals;
    }

    public void setExamenGenerals(Set<ExamenGeneral> examenGenerals) {
        this.examenGenerals = examenGenerals;
    }

    public Set<Internaciones> getInternacioneses() {
        return this.internacioneses;
    }

    public void setInternacioneses(Set<Internaciones> internacioneses) {
        this.internacioneses = internacioneses;
    }

    @Override
    public String toString() {
        return nombre;
    }

}
