package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Propietarios generated by hbm2java
 */
public class Propietarios implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1166179368581605536L;
    private Integer id;
    private Localidades localidades;
    private String nombre;
    private String apellido;
    private String domicilio;
    private String telCel;
    private String telFijo;
    private String mail;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;
    private Set cuentasCorrienteses = new HashSet(0);
    private Set pacienteses = new HashSet(0);

    public Propietarios() {
    }

    public Propietarios(String nombre) {
        this.nombre = nombre;
    }

    public Propietarios(Localidades localidades, String nombre, String apellido, String domicilio, String telCel,
            String telFijo, String mail, Date createdAt, Date updatedAt, Date deletedAt, Set cuentasCorrienteses,
            Set pacienteses) {
        this.localidades = localidades;
        this.nombre = nombre;
        this.apellido = apellido;
        this.domicilio = domicilio;
        this.telCel = telCel;
        this.telFijo = telFijo;
        this.mail = mail;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.cuentasCorrienteses = cuentasCorrienteses;
        this.pacienteses = pacienteses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Localidades getLocalidades() {
        return this.localidades;
    }

    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    public String getTelCel() {
        return this.telCel;
    }

    public void setTelCel(String telCel) {
        this.telCel = telCel;
    }

    public String getTelFijo() {
        return this.telFijo;
    }

    public void setTelFijo(String telFijo) {
        this.telFijo = telFijo;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Set getCuentasCorrienteses() {
        return this.cuentasCorrienteses;
    }

    public void setCuentasCorrienteses(Set cuentasCorrienteses) {
        this.cuentasCorrienteses = cuentasCorrienteses;
    }

    public Set getPacienteses() {
        return this.pacienteses;
    }

    public void setPacienteses(Set pacienteses) {
        this.pacienteses = pacienteses;
    }

}
