package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -1933783350631494110L;
    private int id;
    private int nombre;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;

    public Provincias() {
    }

    public Provincias(int id, int nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Provincias(int id, int nombre, Date createdAt, Date updatedAt, Date deletedAt) {
        this.id = id;
        this.nombre = nombre;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getNombre() {
        return this.nombre;
    }

    public void setNombre(int nombre) {
        this.nombre = nombre;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

}
