package model;
// Generated Apr 30, 2019 5:08:23 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * Provincias generated by hbm2java
 */
public class Provincias extends RecursiveTreeObject<Provincias> implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 6327416101236748155L;
    private int id;
    private Localidades localidades;
    private String nombre;
    private boolean deleted;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;

    public Provincias() {
    }

    public Provincias(Localidades localidades, String nombre, boolean deleted) {
        this.localidades = localidades;
        this.nombre = nombre;
        this.deleted = deleted;
    }

    public Provincias(Localidades localidades, String nombre, boolean deleted, Date createdAt, Date updatedAt,
            Date deletedAt) {
        this.localidades = localidades;
        this.nombre = nombre;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Localidades getLocalidades() {
        return this.localidades;
    }

    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

}
