package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * Retornos generated by hbm2java
 */
public class Retornos extends RecursiveTreeObject<Retornos> implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 8058227608426821990L;
    private Integer id;
    private FichasClinicas fichasClinicas;
    private Date fecha;
    private boolean deleted;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;

    public Retornos() {
    }

    public Retornos(Date fecha, boolean deleted) {
        this.fecha = fecha;
        this.deleted = deleted;
    }

    public Retornos(FichasClinicas fichasClinicas, Date fecha, boolean deleted, Date createdAt, Date updatedAt,
            Date deletedAt) {
        this.fichasClinicas = fichasClinicas;
        this.fecha = fecha;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public FichasClinicas getFichasClinicas() {
        return this.fichasClinicas;
    }

    public void setFichasClinicas(FichasClinicas fichasClinicas) {
        this.fichasClinicas = fichasClinicas;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

}
