package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Tratamientos generated by hbm2java
 */
public class Tratamientos extends BaseModel {

    /**
     *
     */
    private static final long serialVersionUID = -6804007996957015518L;
    private Integer id;
    @NotNull(message = "El campo 'fichasClinicas' es requerido.")
    private FichasClinicas fichasClinicas;
    @NotEmpty(message = "El campo 'tratamiento' es requerido.")
    @Size(max = 200, message = "El campo 'tratamiento' no debe ser mayor a {max} caracteres.")
    private String tratamiento;
    @NotNull(message = "El campo 'fecha' es requerido.")
    private Date fecha;
    @NotNull(message = "El campo 'hora' es requerido.")
    private Date hora;
    private boolean deleted;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;

    public Tratamientos() {
    }

    public Tratamientos(FichasClinicas fichasClinicas, String tratamiento, boolean deleted) {
        this.fichasClinicas = fichasClinicas;
        this.tratamiento = tratamiento;
        this.deleted = deleted;
    }

    public Tratamientos(FichasClinicas fichasClinicas, String tratamiento, Date fecha, Date hora, String procAdicional,
            boolean deleted, Date createdAt, Date updatedAt, Date deletedAt) {
        this.fichasClinicas = fichasClinicas;
        this.tratamiento = tratamiento;
        this.fecha = fecha;
        this.hora = hora;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public FichasClinicas getFichasClinicas() {
        return this.fichasClinicas;
    }

    public void setFichasClinicas(FichasClinicas fichasClinicas) {
        this.fichasClinicas = fichasClinicas;
    }

    public String getTratamiento() {
        return this.tratamiento;
    }

    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    @Override
    public boolean isDeleted() {
        return this.deleted;
    }

    @Override
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    @Override
    public Date getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public Date getDeletedAt() {
        return this.deletedAt;
    }

    @Override
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        return fichasClinicas.toString();
    }

}
