package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * Tratamientos generated by hbm2java
 */
public class Tratamientos extends RecursiveTreeObject<Tratamientos> implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -6804007996957015518L;
    private Integer id;
    @NotNull(message = "El campo 'internaciones' es requerido.")
    private Internaciones internaciones;
    @NotEmpty(message = "El campo 'tratamiento' es requerido.")
    @Size(max = 191, message = "El campo 'tratamiento' no debe ser mayor a {max} caracteres.")
    private String tratamiento;
    @NotNull(message = "El campo 'fecha' es requerido.")
    private Date fecha;
    @NotNull(message = "El campo 'hora' es requerido.")
    private Date hora;
    @Size(max = 191, message = "El campo 'tratamiento' no debe ser mayor a {max} caracteres.")
    private String procAdicional;
    private boolean deleted;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;

    public Tratamientos() {
    }

    public Tratamientos(Internaciones internaciones, String tratamiento, boolean deleted) {
        this.internaciones = internaciones;
        this.tratamiento = tratamiento;
        this.deleted = deleted;
    }

    public Tratamientos(Internaciones internaciones, String tratamiento, Date fecha, Date hora, String procAdicional,
            boolean deleted, Date createdAt, Date updatedAt, Date deletedAt) {
        this.internaciones = internaciones;
        this.tratamiento = tratamiento;
        this.fecha = fecha;
        this.hora = hora;
        this.procAdicional = procAdicional;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Internaciones getInternaciones() {
        return this.internaciones;
    }

    public void setInternaciones(Internaciones internaciones) {
        this.internaciones = internaciones;
    }

    public String getTratamiento() {
        return this.tratamiento;
    }

    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getHora() {
        return this.hora;
    }

    public void setHora(Date hora) {
        this.hora = hora;
    }

    public String getProcAdicional() {
        return this.procAdicional;
    }

    public void setProcAdicional(String procAdicional) {
        this.procAdicional = procAdicional;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

}
