package model;
// Generated Feb 11, 2019 1:52:34 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Vacunas generated by hbm2java
 */
public class Vacunas implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -458942491968433746L;
    private Integer id;
    private Pacientes pacientes;
    private Date fecha;
    private String descripcion;
    private Date createdAt;
    private Date updatedAt;
    private Date deletedAt;

    public Vacunas() {
    }

    public Vacunas(Pacientes pacientes, Date fecha, String descripcion) {
        this.pacientes = pacientes;
        this.fecha = fecha;
        this.descripcion = descripcion;
    }

    public Vacunas(Pacientes pacientes, Date fecha, String descripcion, Date createdAt, Date updatedAt,
            Date deletedAt) {
        this.pacientes = pacientes;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Pacientes getPacientes() {
        return this.pacientes;
    }

    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

}
